version: 0.1

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 775401992551.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t sweethome .
  post_build:
    commands:
      - docker tag sweethome:latest 775401992551.dkr.ecr.us-east-1.amazonaws.com/sweethome:latest
      - docker push 775401992551.dkr.ecr.us-east-1.amazonaws.com/sweethome:latest
